//
//  InstallResponse.swift
//  HumanlabsLinkSDK
//
//  Copyright (c) 2025 HumanlabsLink
//  Licensed under the MIT License
//

import Foundation

/// Response from the install attribution API
public struct InstallResponse: Codable {
    /// Unique install ID generated by the backend
    public let installId: String

    /// Whether this install was attributed to a link click
    public let attributed: Bool

    /// Confidence score for attribution (0-100)
    public let confidenceScore: Double

    /// Which fingerprint factors matched
    public let matchedFactors: [String]

    /// Deep link data if attributed, nil if organic
    public let deepLinkData: DeepLinkData?

    // MARK: - Codable

    enum CodingKeys: String, CodingKey {
        case installId
        case attributed
        case confidenceScore
        case matchedFactors
        case deepLinkData
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        installId = try container.decode(String.self, forKey: .installId)
        attributed = try container.decode(Bool.self, forKey: .attributed)
        confidenceScore = try container.decode(Double.self, forKey: .confidenceScore)
        matchedFactors = try container.decode([String].self, forKey: .matchedFactors)
        // Older Core servers return `deepLinkData: {}` (empty object) instead of
        // null for organic installs. Decoding that as DeepLinkData throws on the
        // required `shortCode`, which would fail the whole install response and
        // silently break deep link callback registration for the session. Treat
        // any undecodable/short-code-less payload as organic (nil).
        deepLinkData = try? container.decodeIfPresent(DeepLinkData.self, forKey: .deepLinkData)
    }

    public init(
        installId: String,
        attributed: Bool,
        confidenceScore: Double,
        matchedFactors: [String],
        deepLinkData: DeepLinkData?
    ) {
        self.installId = installId
        self.attributed = attributed
        self.confidenceScore = confidenceScore
        self.matchedFactors = matchedFactors
        self.deepLinkData = deepLinkData
    }
}

// MARK: - CustomStringConvertible

extension InstallResponse: CustomStringConvertible {
    public var description: String {
        """
        InstallResponse(
            installId: \(installId),
            attributed: \(attributed),
            confidenceScore: \(confidenceScore),
            matchedFactors: \(matchedFactors)
        )
        """
    }
}
