//
//  InstallResponse.swift
//  HumanlabsLinkSDK
//
//  Copyright (c) 2025 HumanlabsLink
//  Licensed under the MIT License
//

import Foundation

/// Response from the install attribution API
public struct InstallResponse: Codable {
    /// Unique install ID generated by the backend
    public let installId: String

    /// Whether this install was attributed to a link click
    public let attributed: Bool

    /// Confidence score for attribution (0-100)
    public let confidenceScore: Double

    /// Which fingerprint factors matched
    public let matchedFactors: [String]

    /// Deep link data if attributed, nil if organic
    public let deepLinkData: DeepLinkData?

    // MARK: - Codable

    enum CodingKeys: String, CodingKey {
        case installId
        case attributed
        case confidenceScore
        case matchedFactors
        case deepLinkData
    }
}

// MARK: - CustomStringConvertible

extension InstallResponse: CustomStringConvertible {
    public var description: String {
        """
        InstallResponse(
            installId: \(installId),
            attributed: \(attributed),
            confidenceScore: \(confidenceScore),
            matchedFactors: \(matchedFactors)
        )
        """
    }
}
